# Generated by Django 3.2 on 2022-12-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dto_pack.enum
import uuid
import wallets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.CharField(default=wallets.models.create_transfer_number, max_length=25, unique=True)),
                ('status', models.CharField(choices=[(dto_pack.enum.TransferStatus['Init'], 'Init'), (dto_pack.enum.TransferStatus['Pending'], 'Pending'), (dto_pack.enum.TransferStatus['Succeed'], 'Succeed'), (dto_pack.enum.TransferStatus['Failed'], 'Failed'), (dto_pack.enum.TransferStatus['Canceled'], 'Canceled')], default=dto_pack.enum.TransferStatus['Init'], max_length=10)),
                ('type', models.CharField(choices=[(dto_pack.enum.TransferType['Withdraw'], 'Withdraw'), (dto_pack.enum.TransferType['Deposit'], 'Deposit')], default=dto_pack.enum.TransferType['Deposit'], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('from_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_transfers', to='banks.bankaccount')),
                ('to_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transfers', to='banks.bankaccount')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallets.transaction')),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wallets.wallet'),
        ),
    ]
