# Generated by Django 3.2 on 2022-12-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='scheduled_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
