# Generated by Django 3.2 on 2022-12-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_transfer_scheduled_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='scheduled_id',
            new_name='schedule_id',
        ),
    ]
